# Generated by Django 4.2.3 on 2023-07-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('tampico', 'Tampico'), ('altamira', 'Altamira'), ('cd. mader', 'Cd. Madero'), ('otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(choices=[('tamaulipas', 'Tamaulipas'), ('veracruz', 'Veracruz'), ('otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
