# Generated by Django 4.2.3 on 2023-07-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_auth_age_customuser_send_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_age',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='send_mail',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='terms_conds',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
