# Generated by Django 4.2.3 on 2023-07-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_auth_age_alter_customuser_send_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_age',
            field=models.CharField(default='False', max_length=50, null=True),
        ),
    ]
