# Generated by Django 4.2.3 on 2023-07-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_auth_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='send_mail',
            field=models.CharField(default='False', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='terms_conds',
            field=models.CharField(default='False', max_length=50, null=True),
        ),
    ]
