# Generated by Django 4.2.3 on 2023-07-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_auth_age_alter_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_age',
            field=models.BooleanField(default=False),
        ),
    ]
