# Generated by Django 4.2.3 on 2023-07-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_auth_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='send_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='terms_conds',
            field=models.BooleanField(default=False),
        ),
    ]
