# Generated by Django 4.2.3 on 2023-07-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
