# Generated by Django 4.2.3 on 2023-07-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('date1', models.DateField(null=True)),
                ('date2', models.DateField(null=True)),
                ('date3', models.DateField(null=True)),
                ('date4', models.DateField(null=True)),
                ('location', models.CharField(max_length=50)),
                ('ticket_price', models.CharField(max_length=50)),
            ],
        ),
    ]
