# Generated by Django 4.2.3 on 2023-07-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butaca', '0004_event_city_event_country_event_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bann_img',
            field=models.ImageField(default='', upload_to='event_galery/'),
        ),
        migrations.AddField(
            model_name='event',
            name='min_img',
            field=models.ImageField(default='', upload_to='event_galery/'),
        ),
    ]
