# Generated by Django 4.2.3 on 2023-07-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butaca', '0008_alter_event_bann_img_alter_event_min_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bann_img',
            field=models.ImageField(blank=True, default='', upload_to='event_galery'),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_img',
            field=models.ImageField(blank=True, default='', upload_to='event_galery'),
        ),
    ]
