# Generated by Django 4.2.3 on 2023-07-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butaca', '0010_remove_dateevent_id_dateevent_date_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateevent',
            name='name',
        ),
        migrations.AddField(
            model_name='dateevent',
            name='event',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
