# Generated by Django 4.2.3 on 2023-07-21 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('butaca', '0011_remove_dateevent_name_dateevent_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawTicket',
            fields=[
                ('draw_ticket_id', models.CharField(default='1', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('date_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butaca.dateevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
