# Generated by Django 4.2.3 on 2023-07-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butaca', '0013_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
