# Generated by Django 4.2.3 on 2023-07-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butaca', '0014_remove_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateevent',
            name='ticket_quantity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
