# Generated by Django 4.2.3 on 2023-07-21 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('butaca', '0015_dateevent_ticket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='promoter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotor', to=settings.AUTH_USER_MODEL),
        ),
    ]
