# Generated by Django 4.2.3 on 2023-07-23 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('butaca', '0018_dateevent_promoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateevent',
            name='event_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='butaca.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='promoter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoter', to=settings.AUTH_USER_MODEL),
        ),
    ]
