# Generated by Django 4.2.3 on 2023-07-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butaca', '0019_dateevent_event_name_alter_event_promoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bck_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='event_galery'),
        ),
    ]
