# Generated by Django 4.2.3 on 2023-07-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butaca', '0021_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateevent',
            name='ticket_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
